### ISSUE TITLE
Doc:  --transform_policy/-t option is missing default

### ISSUE THREAD

**Issue by rugk** [containers/podman-compose#315]
There is the help output…

```
$ podman-compose --help
usage: podman-compose [-h] [-f file] [-p PROJECT_NAME] [--podman-path PODMAN_PATH] [--no-ansi] [--no-cleanup] [--dry-run] [-t {1pod,1podfw,hostnet,cntnet,publishall,identity}]
                      {help,version,pull,push,build,up,down,ps,run,start,stop,restart,logs} ...

optional arguments:
  -h, --help            show this help message and exit
  -f file, --file file  Specify an alternate compose file (default: docker-compose.yml)
  -p PROJECT_NAME, --project-name PROJECT_NAME
                        Specify an alternate project name (default: directory name)
  --podman-path PODMAN_PATH
                        Specify an alternate path to podman (default: use location in $PATH variable)
  --no-ansi             Do not print ANSI control characters
  --no-cleanup          Do not stop and remove existing pod & containers
  --dry-run             No action; perform a simulation of commands
  -t {1pod,1podfw,hostnet,cntnet,publishall,identity}, --transform_policy {1pod,1podfw,hostnet,cntnet,publishall,identity}
                        how to translate docker compose to podman [1pod|hostnet|accurate]

command:
  {help,version,pull,push,build,up,down,ps,run,start,stop,restart,logs}
    help                show help
    version             show version
    pull                pull stack images
    push                push stack images
    build               build stack images
    up                  Create and start the entire stack or some of its services
    down                tear down entire stack
    ps                  show status of containers
    run                 create a container similar to a service to run a one-off command
    start               start specific services
    stop                stop specific services
    restart             restart specific services
    logs                show logs from services
```

…and [there is this doc in the repo](https://github.com/containers/podman-compose/blob/devel/docs/Mappings.md) (BTW is that published on GItHub Pages or so somewhere, as it is hard to find in a repo?)

Especially the last document is nice as it explains all those cryptic transform policy names (:see_no_evil:), however, it fails to mention one thing: **What is actually the default mode?**

From my experience I guess it is `1pod`, but it says  "(does not work)" in the doc at least… so I'm somewhat confused. :sweat_smile: 

## System

```
$ podman-compose version
using podman version: podman version 3.2.0
podman-composer version  0.1.7dev
podman --version
podman version 3.2.0
0
$ podman version
Version:      3.2.0
API Version:  3.2.0
Go Version:   go1.16.3
Built:        Wed Jun  9 16:24:16 2021
OS/Arch:      linux/amd64
```

**Comment by samarthj** [comment]
According to the [readme](https://github.com/containers/podman-compose#how-it-works) `1podfw` is the default and that is what I have noticed while running in default mode as well. The default in code is [here](https://github.com/samarthj/podman-compose/blob/502d7cc206da1f20cc9aef480f93f6b32d576f80/podman_compose.py#L1180).

I would suggest starting with `identity` if you want to use a 1:1 mapping with docker-compose, and then modifying your base from there. It basically uses exactly what you specify in the compose file, no more, no less. Aside from dnsname giving you the mappings via container names for free, that is if you built your network using podman>=3.2.3 (approximating here, don't remember the exact release they defaulted to using the dnsname plugin for the networks).

I believe that doc is a bit old, and needs an update. Networking in podman has improved quite a bit since then, particularly with rootless cnis and dnsname. And there is possibly some room for improving the default as well.

**Comment by muayyad-alsadi** [comment]
I would love to switch to identity after implementing `podman network create`
it was not `dnsname`, it's about `slirp4netns`

at the time I started `podman-compose`,  user-land network `slirp4netns` did not support intern-container communication
so we did several attempt to hack that suuport by sharing network namespace and map everything to localhost of the container (
that is `1pod,1podfw,hostnet,cntnet`)

newer versions of slirp4netns/podman do support inter-container communication

```
podman network create mynet
```

then run two containers in two tabs using

```
podman run --network network:mynet --rm -ti busybox /bin/sh
```

then type `ifconfig` and start  testing with "nc" and "busybox httpd"

things seems fine, I need away to detect if `podman network create` works in user land and make that is the default.
do you know a quick way to do this detection?

**Comment by rugk** [comment]
Sure and thanks for the suggestions. Though this issue of course is mostly about the doc. And if you want to take this issue to revise the doc in general, feel free to do that, of course. :slightly_smiling_face:

**Comment by samarthj** [comment]
@rguk 
You are right of course, the issue is about the tool documentation. I will add the default once I get a moment. :slightly_smiling_face: 


@muayyad-alsadi 
Verifiable detection may be complex, or at least I don't know of a straightforward way of telling what the user is using. But I am also thinking whether podman-compose should worry about that though. Having the default in `identity` would convey: 

> The stack would be set up exactly how it is specified in the compose file + whatever the user has configured their podman to do. If they would like to change how any of that functions, then here are the different flavors in `1pod`, `1podfw`, etc to modify that on a compose-by-compose basis.

This was probably not viable before, but from what I can tell the inter-container communication in the rootless mode now works pretty seamlessly and for both pure slirp4netns and CNI modes. The default from [3.3.0](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md#330) appears to set up CNIs as well.

> Podman will now automatically create the default CNI network if it does not exist, for both root and rootless users. This will only be done once per user - if the network is subsequently removed, it will not be recreated.

So I believe, CNI in root or CNI-in-slirp4netns in rootless is the default behavior now. I am using the dev version though, and have been for a while, and need to test it on actual older release versions to say anything definitive about it. To run a container in pure slirp4netns mode I need to explicitly specify it during container creation. 

So as far as using CNIs goes, one could inspect the network and say that if the `dnsname` plugin is being used, then communication will work, and call that good. If not (I think creating CNIs before 3.2 did not include the plugin by default, now `--disable-dns` is its own flag, which was added in slirp4netns 1.1.0), then communication will not work.

Pure slirp4netns is its own thing though and I don't think I have played around with it enough.

I am happy to talk more and dive deeper with it if you are interested in exploring this further though.

**Comment by muayyad-alsadi** [comment]
> So I believe, CNI in root or rootless-CNI in rootless is the default behavior now. 
On my podman 3.3.0, when I "podman run", all containers have same IP, thus no inter-container communication, unless there is `podman create network mynet` and `podman run --network network:mynet` 

currently podman-compose do not create this network, and I'm sure older podman do not support `podman run --network network:mynet`

**Comment by samarthj** [comment]
Yup, sounds familiar. 

Try recreating your default network `podman` that is used on `podman run`. If podman was upgraded normally, it would not have touched the old network if it existed. 

Since they changed it, I think it was the simplest way to retain back-compat. The recreation might still happen in v4, which is the next target release, but I doubt it. The statement:
 
>This will only be done once per user - if the network is subsequently removed, it will not be recreated.` 

conveys to me that future network-related changes are going to be handled similarly. Which sounds reasonable, to be honest. Just maintaining a default behavior for it seems tricky, and imagining it kind of freaks me out a bit. I prefer to specify everything though, so maybe I'm an odd duck.  :stuck_out_tongue:

Back to podman-compose, since networks are not implemented, the way I use it at the moment is specifying a specific external network as default network_mode, that way things just work as I expect them, no matter where things change. But using the default works as well since I did recreate the default network.

I guess if network creation is implemented in podman-compose, it would be a more compelling sell for `identity` being the default. As it stands though maybe not?

**Comment by rugk** [comment]
As far as it seems this issue here was fixed by https://github.com/containers/podman-compose/pull/332? But as you still discuss things, I'll leave it open, though I currently don't understand what you're discussing here… maybe better open a new issue?

**Comment by samarthj** [comment]
I think you can close it if you want, I don't mind at all. We are talking more about if `identity` could take the place of `1podfw` and what it would take for it to make that happen. Without a `networks` implementation and with the newness of the implementation rootless CNIs in podman itself, it doesn't seem to be adding a lot of value at the moment. Until it becomes more relevant, I don't have more to add on the topic. :upside_down_face:
I can reference it in a separate issue at a later time. Since it is not just a documentation thing, it would probably be better to have a dedicated issue.

**Comment by rugk** [comment]
Okay fine, so better open that dedicated issue then… :upside_down_face:
