### ISSUE TITLE
Podman-compose no longer create pods

### ISSUE THREAD

**Issue by mnsmithuk** [containers/podman-compose#391]
Hi

I was previously using podman-compose 0.17dev on CentOS7. I have since migrated to CentOS8 and downloaded the latest podman-compose 1.0.3 (with podman 3.2.3 installed using the install intructions from podman.io) and the new version does not create pods.  Is this a bug or  new feature to  imitate how docker-compose works?

**Comment by lmsyx** [comment]
@mnsmithuk it is a new feature, please refer to #379

**Comment by muayyad-alsadi** [comment]
you can use latest 0.1.x if you really really want this.

creating a pod with shared network allowed inter-container communication via localhost (inside the pod)
because there was no intern-container communication at that time.

now podman support "podman create network mynet" and it supports inter-container communication, the workaround no longer needed.

**Comment by mnsmithuk** [comment]
ok thanks @muayyad-alsadi and @lmsyx for clearing that up.  So when are pods supposed to be used in podman?

Are there any benefits using podman-compose over docker-compose now that podman 3.x supports docker-compose ?

**Comment by muayyad-alsadi** [comment]
daemon-less and process model: there is no daemon in podman-compose.

speed: when you type pomdna-compose build, there is no large tarball of context sent to the "remote" daemon.

security: same user, there is no fat daemon running as root and permission hell between the command and the daemon
ex. running docker-compose as user A while the daemon is running as user B

**Comment by mnsmithuk** [comment]
Ok. Great thanks.
