### ISSUE TITLE
Extend the compose spec to add rootful containers to compose files without making the whole stack rootful

### ISSUE THREAD

**Issue by BLucky-gh** [containers/podman-compose#439]
## **Is your feature request related to a problem? Please describe.**
Right now I have a stack that has a couple of rootless containers and one rootful container for the sole purpose to binding to port 80 and I can't seem to find a way to make just that one container rootful

## **Describe the solution you'd like**
Add a way to specify specific containers in the compose file as rootful

## **Describe alternatives you've considered**
I've considered just having a rootless compose file and then run the rootful container manually but that defeats the point of orchestration with compose.
I also considered a reverse proxy but I would like to have the reverse proxy run in the container which brings us back to the first issue.

**Comment by muayyad-alsadi** [comment]
> I've considered just having a rootless compose file and then run the rootful container manually but that defeats the point of orchestration with compose.
> I also considered a reverse proxy 

don't dismiss this idea, this is not bad idea at all

you run your non-privileged application on a non-privileged port
and elsewhere you run a buffering privileged reverse proxy on the privileged port

why this is good idea

1. there is no moving parts in the reverse proxy (smaller attack surface)
2. you should not expose your application directly to the public, you need a buffering reverse proxy in-front of it anyway (a syn flood would block the application, but it won't block an event driven reverse proxy)
3. after opening the port, the reverse proxy [daemon](https://man7.org/linux/man-pages/man7/daemon.7.html) drops privileges using the double fork technique  
4. you can bound the root and drop its capabilities (creating unprivileged root) using system'd `CapabilityBoundingSet`

```
# /etc/systemd/system/nginx.service.d/cap.conf
[Service]
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
```

> the point of orchestration with compose.

we might need to integrate with something like [traefik](https://github.com/traefik/traefik)

typically you specify a special label for the hostname or url prefix (route)
and the proxy observe that and route the traffic to the container

```
podman run -d -l "traefik.frontend.rule=Host:test.localhost;PathPrefix:/test" myapp
```

or write it to some sort of store like redis or etcd or consul or even a srv record in DNS

long long a go I made haproxy that integrates with docker and I called it [docker-glue](https://github.com/muayyad-alsadi/docker-glue).

> Add a way to specify specific containers in the compose file as rootful

this is not possible, why? because we are not supposed to have a privileged daemon in podman.
the compose run as the current user, it does not pass the commands to a remote daemon running as a different user.

if you want privileged rootful you run it with sudo

> I also considered a reverse proxy but I would like to have the reverse proxy run in the container which brings us back to the first issue.

you can ask the kernel to do that if you don't want to run reversed proxy

```
ipvsadm -A -t 127.0.0.1:80 -s rr
ipvsadm -a -t 127.0.0.1:80 -r 127.0.0.1:8080 -m
```

NOTE: `rr` for round robin, `lc` least connected, `lblc` sticky lc
