### ISSUE TITLE
Cannot successfully bring up tests/nethost/docker-compose.yml

### ISSUE THREAD

**Issue by detwiler** [containers/podman-compose#512]
**Describe the bug**
With a fresh Fedora 36 install, and the latest development branch of podman-compose, the stack at [tests/nethost/docker-compose.yml](https://github.com/containers/podman-compose/blob/devel/tests/nethost/docker-compose.yaml) fails to come up.

**To Reproduce**
1. Start with a fresh Fedora 36 install.

```
$ sudo dnf --refresh upgrade
$ sudo dnf install @container-management podman-compose
$ sudo dnf remove --noautoremove podman-compose
$ pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
$ git clone https://github.com/containers/podman-compose.git
$ cd podman-compose/tests/nethost
$ podman-compose up
```

**Expected behavior**
The stack successfully comes up.

**Actual behavior**
Stack fails to come up with error message about network mode.

**Output**

```
$ podman-compose version
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.1.1
podman-composer version 1.0.4
podman --version 
podman version 4.1.1
exit code: 0

$ podman-compose up
podman-compose version: 1.0.4
['podman', '--version', '']
using podman version: 4.1.1
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=nethost', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_nethost --infra=false --share=
7638424b3addf73e8dc5a4eb38028e334748772e1a2339a9e21120b89aeb03af
exit code: 0
podman create --name=nethost_web_1 --pod=pod_nethost --label io.podman.compose.config-hash=03bfd542c97d0107843de00920b9c6afe868ad762777314721d075cf88b5a24e --label io.podman.compose.project=nethost --label io.podman.compose.version=1.0.4 --label com.docker.compose.project=nethost --label com.docker.compose.project.working_dir=/home/vagrant/work/ref/podman-compose/tests/nethost --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=web --network host --net nethost_default --network-alias web busybox httpd -f -p 8123 -h /etc/
Error: cannot set multiple networks without bridge network mode, selected mode host: invalid argument
exit code: 125
podman start -a nethost_web_1
Error: no container with name or ID "nethost_web_1" found: no such container
exit code: 125
```

**Environment:**
 - OS: Linux - Fedora 36
 - podman version: 4.1.1
 - podman compose version: 1.0.4

**Additional context**

I tried the steps that were linked in [this comment](https://github.com/containers/podman-compose/issues/500#issuecomment-1153225803), but that did not solve the issue for me.

**Comment by DynamoFox** [comment]
Hello, I think I'm facing a similar issue which has the same root cause.

compose.yaml:
```
services:
  webserver-front:
    image: docker.io/caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    network_mode: "slirp4netns:port_handler=slirp4netns"
```
This compose file raises the following error:
`Error: cannot set multiple networks without bridge network mode, selected mode slirp4netns: invalid argument`

And here's the command executed by _podman-compose_ to create the container that causes the error: (N.B. : I have stripped from it some --label(s))
```
podman create --name=web-apps-compose_webserver-front_1 \
--network slirp4netns:port_handler=slirp4netns \
--net testme_default --network-alias webserver-front -p 80:80 -p 443:443 docker.io/caddy:alpine
```
The issue seems to arise by the fact that the following parameters are appended: `--net` and `--network-alias`, despite them not being required (I guess...) and despite them being seemingly incompatible with the 'network_mode' specified in the compose file. This behavior was already documented in #500.

If I just remove `--net` (leaving --network-alias) I get another error:
'Error: --network-alias can only be set when the network mode is bridge: invalid argument'

On the other hand, if I remove **both** the parameters the container runs just fine.

What's more curious is that in another Compose I tested the `--net' parameter comes with **just** a white-space as a value before being followed by another parameter.

It should be noted this was reproduced using podman-compose with version 1.0.3

**Comment by muayyad-alsadi** [comment]
I've just pushed a fixed, please test.

```
pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
```

> What's more curious is that in another Compose I tested the `--net' parameter comes with just a white-space as a value before being followed by another parameter.

I would like to see this compose file.

**Comment by DynamoFox** [comment]
Nice, now podman-compose produces for the compose.yaml in my previous reply the following (stripped --label(s)):
```
podman create --name=testme_webserver-front_1 --pod=pod_testme --network slirp4netns:port_handler=slirp4netns -p 80:80 -p 443:443 docker.io/caddy:alpine
```
And as a result it runs just fine :3

Somebody should test if this solves the broken test case initially reported by the author of this issue.

> I would like to see this compose file.

It happened in a container with network_mode: "slirp4netns:port_handler=slirp4netns" in a more elaborate compose file, it's probably related to the bug in this issue, it should be fixed now but I can't test it yet, if I notice it happens again I'll open a new issue.

**Comment by detwiler** [comment]
I can confirm that this fixed the issue for the `nethost` test as well as my personal stack which uses `network_mode: host`. Thank you very much!

**Comment by mohd-akram** [comment]
Hope a new version can be pushed with the fix soon as our compose files are currently broken because of this. Seems like there hasn't been a release in quite a while.

**Comment by akosveres** [comment]
+1 on a release, try has broken my podman setup as well.
