### ISSUE TITLE
Issue with Podman 4.1.1 - Error: invalid config provided: extra host entries must be specified on the pod

### ISSUE THREAD

**Issue by ketanb02** [containers/podman-compose#539]
**Describe the bug**
Unable to start the container using podman-compose with podman version 4.1.1

**To Reproduce**
1. podman-compose -f <compose.yml> up

**Expected behavior**
Container should be up and running. Same yml working fine with podman version 4.0.2

**Actual behavior**
Getting error 
Error: invalid config provided: extra host entries must be specified on the pod: network cannot be configured when it is shared with a pod
125

**Version**
using podman version: podman version 4.1.1
podman-composer version  0.1.7dev
podman --version
podman version 4.1.1

**yml**

I have added the extra_hosts in compose but no luck.
    extra_hosts:
      - "host:IP"

If i run directly using podman by adding --add-host, it works

**Comment by muayyad-alsadi** [comment]
You have too old podman-composer version

podman-composer version 0.1.7dev

Please install latest 1.x version

**Comment by robbmanes** [comment]
Just noting I think this is happening because of a change to podman 4.1 from 4.0.  Specifically, this appears to be happening because of https://github.com/containers/podman/commit/e4ab8a5bedb48615402231a5aa3a62ca4364c45f, which disallows specifying additional --add-host entries when creating a container that is going to be in an already existing pod, as we now seem to expect all host entries to be present at pod creation.

From reading `podman-compose` since secondary containers in a pod are passed with the `--add-host` option when the `extra_hosts` tag is present in the `compose.yml`, then we see the error `invalid config provided: extra host entries must be specified on the pod: network cannot be configured when it is shared with a pod`.

I believe the podman behavior is correct in 4.1, but I was able to revert to 4.0 prior to the above patch and the issue went away.

I think we'd have to have podman-compose be aware of "first container" operations within the pod, no?  So we'd have to avoid passing `--add-host` arguments to the secondary containers within a pod to avoid problems like this when calling `podman create`.  I'm new to this codebase so I'm unsure if that's a valid solution.

**Comment by muayyad-alsadi** [comment]
podman-compose 0.x used to use --add-host, recent podman-compose don't use that. we use DNS plugin. please upgrade your compose

**Comment by makeitstatic** [comment]
I have this issue running containers in a pod with podman only, not using compose.
Does the recent updates in podman mean that I should use some podman DNS settings instead of --add-host appserver:127.0.0.1 when I run my container?
