### ISSUE TITLE
podman-compose doesn't survive a reboot

### ISSUE THREAD

**Issue by t1diotac** [containers/podman-compose#587]
Coming from docker-compose I expected a reboot to be more seamless. But a reboot seems to have sent my containers into oblivion and required a bit of cleanup to get them to a point of being able to start again.

Things like:
`podman-compose logs`
Don't seem like they would work when I look at the various solutions for containers working through a reboot (systemd seems to be the most commonly proposed solution) since it appears they look at each container individually and not as a related set of apps (it appears they used to start as pods, and that seems like it solves that issue but that is no longer the situation).

The only alternative I've considered is throwing Docker on this system, but really I'd prefer to stick with Podman and podman-compose. It seems like a better way forward if I can solve my issues.

This is Rocky Linux 9, podman 4.1.1, podman-composer version  1.0.3

My docker-compose.yml is a pretty out-of-the-box version of this, with minor changes and various user/pass changes to fit my specific needs:
https://github.com/nightscout/cgm-remote-monitor/blob/master/docker-compose.yml

**Comment by t1diotac** [comment]
To sort of piggyback on my previous example/question:

If I perform the following:
`podman-compose up -d && podman-compose stop`
Do I then create 2 separate systemd files:
`podman generate systemd --name nightscout --files && mv container-nightscout.service ~/.config/systemd/user/`
`podman generate systemd --name mongo --files && mv container-mongo.service ~/.config/systemd/user/`

If so, it seems like a less containerized solution. For other multi-service docker-compose.yml that use mongo and/or nightscout, Does my next .service file become container-mongo1.service? 6 months down the road, when I look at .config/systemd/user and see mongo.service and mongo1.service, how do I know which belongs to which compose "group"?

Thanks for any clarification/help in understanding.

**Comment by anutator** [comment]
You must upgrade to podman-compose 1.0.4 and add a service to systemd. You can name your podman-compose file as a service name, for example  api.yaml
sudo podman-compose systemd -a create-unit`
podman-compose -f api.yaml systemd -a register 
systemctl --user start podman-compose@api
systemctl --user enable podman-compose@api

**Comment by tsteiner** [comment]
I'm having trouble finding version 1.0.4.  The latest seems to be 1.0.3.  Can you point me in the right direction?

**Comment by klemendlabs** [comment]
I have the same question as @tsteiner (I'm running Centos 8 Stream, latest updates - podman-compose-1.0.3-3.el8.noarch)

**Comment by jiaming0708** [comment]
Do you have any release plan for 1.0.4?

**Comment by muayyad-alsadi** [comment]
I've just released 1.0.6

if you want the new behavior pass `--in-pod=1` this will be the default in `1.1.x`

**Comment by CayoM** [comment]
@muayyad-alsadi can you please explain how --in-pod=1 solve the issue, that podman-compose is not bootsafe? The only thing, that helped me keep running the containers was the instructions from @anutator and this was already possible in a previous release.

**Comment by muayyad-alsadi** [comment]
> can you please explain how --in-pod=1 solve the issue, that podman-compose is not bootsafe? 

bootsafty is not related to `--in-pod`, that was an answer to "Do you have any release plan for 1.0.4?"

many users like @jiaming0708 @Igetin that you need 1.0.4 but it's not yet released at that time
my comment says it's released and you can use it just mind the following breaking change

old stable (1.0.3) and new stable (1.0.6) have same behavior (no pod is created by default)
old devel (1.0.4) and new devel (1.0.7) have same behavior (a pod is created and all containers lives inside it)

if you upgraded to the latest stable version 1.0.6 and you want different behavior use `--in-pod=0|1`

you just need to create a systemd that starts the containers
either using podman-compose (via `podman-compose systemd` ) or podman (via `podman generate systemd`)

podman creates a systemd unit for every single container
podman-compose creates a single unit for the entire stack
it's up to your preference

just make sure the user you use can have services using:

```
sudo loginctl enable-linger '{username}'
```

**Comment by teras** [comment]
> You must upgrade podman-compose to 1.0.4 version and add a service to systemd. You can name your podman-compose file as a service name, for example api.yaml
> 
> ```shell
> podman-compose systemd -a create-unit
> ```

I am using podman-compose 1.0.6

When I run the above command, I get error message
```Could not write to [/etc/systemd/user/podman-compose@.service], use 'sudo'```
But when I use sudo, of course "podman-compose" as a command is not recognized -- and I believe for a good reason. I don't want to create a systemd service with root as the owner, instead of my own user.

Maybe I am missing something here?

**Comment by jzcad1828** [comment]
> > You must upgrade podman-compose to 1.0.4 version and add a service to systemd. You can name your podman-compose file as a service name, for example api.yaml
> > ```shell
> > podman-compose systemd -a create-unit
> > ```
> 
> I am using podman-compose 1.0.6
> 
> When I run the above command, I get error message `Could not write to [/etc/systemd/user/podman-compose@.service], use 'sudo'` But when I use sudo, of course "podman-compose" as a command is not recognized -- and I believe for a good reason. I don't want to create a systemd service with root as the owner, instead of my own user.
> 
> Maybe I am missing something here?

I had the same problem and realized it's trying to write to a system folder. I went the long way to realizing (created sudoers file for pod user, not ideal) that `podman-compose systemd -a create-unit` is required to be run as root initially, and after reading the command usage I believe this is a one time command for the system. Once it's done, you can log back in as the container user and use the `podman-compose -a register`  or `podman-compose -f file.yml -a register` (while in project folder) in order to create the user systemd files. Then you can enable and start the service with `systemctl --user enable --now podman-compose@<project>`. Hope this helps!

**Comment by jzcad1828** [comment]
I do however have the problem when I try to start the services after creating multi-container compose files.

Creation command:
$ podman-compose --in-pod=1 systemd -a register

`Job for podman-compose@asdfasdf.service failed because the control process exited with error code.
See "systemctl --user status podman-compose@sadfasdf.service" and "journalctl --user -xeu podman-compose@asdfasdf.service" for details.`

podman[155064]: Error: no pod with name or ID pod_asdfasdf found: no such pod

`$ cat /etc/redhat-release;podman-compose --version
AlmaLinux release 9.2 (Turquoise Kodkod)
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.4.1
podman-compose version 1.0.6
podman --version 
podman version 4.4.1
exit code: 0`

Furthermore, I can't seem to figure out how to remove deleted service entries from `podman-compose systemd -a ls` - I see several that are tests and no longer exist, but there's no unregister command.

**Comment by jzcad1828** [comment]
Yep, not sure how this was ever supposed to work. Podman-compose removed pod creation with 1.0.x release. podman-compose systemd command refuses to create pod, but the service file created by this command attempts to start non-existent pods. Either I'm missing something or this process just doesn't work. I have tried with --in-pod=1 and --in-pod=0 for both the systemd create-unit and register commands, can't make this work. :/

**Comment by qupfer** [comment]
Just a information for googler's and bing'ers who find this thread as I did and how it worked for me. 
The commands are just from memory, so there may be some typos or mistakes.
I'm running a ubuntu 22.04 machine, the is still podman-compose 1.0.3.

First: get podman-compose devel (in a virtuel env)
`sudo apt install python3-virtualenv`
`python3 -m virtualenv ~/compose_venv`
`source ~/compose_venv/bin/activate`
`pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz`

Then run the venv compose as sudo:
`sudo ~/compose_venv/bin/podman-compose systemd -a create-unit`

Now no-sudo register the project (still with activated venv)
`cd my/Compose/Project`
`podman-compose systemd -a register`
`systemctl --user enable --now podman-compose@project-name`

After all, remove the devel-compose
`deactive`
`rm -rf  ~/compose_venv`

**Comment by ucekmez** [comment]
@qupfer thanks for the clarification. What you explained works. Although the containers are created after the register command, they never get to start unless the user (if not root) logs in manually. Do we have any followpaths on that, where the pods start in the name of the non-root user, but doesn't require you to login?

**Comment by qupfer** [comment]
> @qupfer thanks for the clarification. What you explained works. Although the containers are created after the register command, they never get to start unless the user (if not root) logs in manually. 

This sounds for me like missing enable „lingering“
(Google Systemd enable lingering or `loginctl enable-linger username`

**Comment by rdlmda** [comment]
This seems relevant: https://linuxhandbook.com/autostart-podman-containers/
