### ISSUE TITLE
podman build dockerfile in compose.yml but try to pull from docker.io

### ISSUE THREAD

**Issue by timeroute** [containers/podman-compose#594]
**podman build dockerfile in compose.yml but try to pull from docker.io**

A docker-compose.yml file like as follow:
```
version: '3.9'

services:
  server:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - .env
    restart: 'always'
    depends_on:
      - database
    networks:
      - push-api

...
```

**Output**

```
$ podman-compose up -d

...
Resolving "server" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull docker.io/library/server:latest...
Error: initializing source docker://server:latest: (Mirrors also failed: [docker.mirrors.ustc.edu.cn/library/server:latest: pinging container registry docker.mirrors.ustc.edu.cn: invalid status code from registry 403 (Forbidden)]): docker.io/library/server:latest: reading manifest latest in docker.io/library/server: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
...
```

**Environment:**
 - OS: Linux
 - podman version: 4.3.1
 - podman compose version: 1.0.3

**Comment by benyaminl** [comment]
Uhm if the Dockerfile is included image that's not.... available in local then it will fetch the image, in podman, if you have Dockerfile/Containerfile, you need to set the full image path, example from redhat registry you need to write

```Dockerfile
FROM registry.access.redhat.com/ubi9:9.1.0-1646
RUN ..

CMD ...
```

**Comment by fourstepper** [comment]
@benyaminl

@timeroute expects podman-compose to build the image to be used, similarly to how docker-compose does

**Comment by benyaminl** [comment]
@fourstepper It's but that doesn't mean it default to docker.io.... as the containers.conf on podman has different ways to interpret it... you can't expect it to resolve it to docker.io by default... 

Take example, docker-compose doesn't support :Z and :z flag.... but podman-compose does... does that means it should be 100% compatible by doesn't supporting SELINUX as podman works on SELINUX environment... 

It's my thought, anyone is free to open pull request, but as I know, it's on podman side not docker side... you can't make it default to docker.io, when a lot of people who use podman-compose on RHEL/Fedora environment that has default to RHEL UBI container, that only has register.access.redhat.com on their container.conf overriden by docker.io.

see https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md

**Comment by fourstepper** [comment]
That’s completely unrelated, isn’t it?

**Comment by benyaminl** [comment]
@fourstepper it's related man... if you only set docker.io on the registry, it will directly by default resolve to pull only from docker.io, and that solve the problem @timeroute asked on this issue... 

Because by default when you have more than one container registry repo config on podman, then it will ask for it. 

Take example, on rhel you only have quay or redhat registry, then this Dockerfile 

```dockerfile
FROM ubi9:9.1.0-1646
```

directly resolve to registry.access.redhat.com/ubi9:9.1.0-1646

as simple as that, podman only resolve depends on your local settings... that's why I said, don't break that things, because most of user on enterprise use the container-registries.conf. some use Openshift, yeah, but... on the RHEL development server... :/
