### ISSUE TITLE
Port in docker-compose is ignored

### ISSUE THREAD

**Issue by Vic-M** [containers/podman-compose#736]
**Describe the bug**
podman-compose is ignoring the port set in the docker-compose.yml file

**To Reproduce**
docker-compose.yml:
```
version: "3.8"
services:
  ftp:
    image: "docker.io/delfer/alpine-ftp-server"
    ports:
      - 1082:21
```

run `podman-compose.yml`

**Expected behavior**

`podman ps` should produce
`e8a6f1282e8d  docker.io/delfer/alpine-ftp-server:latest                        About a minute ago  Up About a minute  0.0.0.0:1082->21/tcp  development_ftp_1`

**Actual behavior**
`podman ps` should produces
`e8a6f1282e8d  docker.io/delfer/alpine-ftp-server:latest                        About a minute ago  Up About a minute  0.0.0.0:36809->64941/tcp  development_ftp_1`

Podman settings generated by podman-compose:
```
$ podman-compose up -d
podman-compose version: 1.0.7
['podman', '--version', '']
using podman version: 4.6.0-rc2
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=development', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_development --infra=false --share=
94cc1c0523a105a961ab9348c427719337e26f20c946b9c9a1fbffecdcb1bab8
exit code: 0
['podman', 'network', 'exists', 'development_default']
podman run --name=development_ftp_1 -d --pod=pod_development --label io.podman.compose.config-hash=39ba7fac1094bfb46b073294a9942b4ce801643434a773dd733334dab5467091 --label io.podman.compose.project=development --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@development.service --label com.docker.compose.project=development --label com.docker.compose.project.working_dir=/apps/medphys-server/server/development --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=ftp --net development_default --network-alias ftp -p 64941 docker.io/delfer/alpine-ftp-server
4eed6982648bdd0aa0513ca1dd82acef4b398de676201f52d514cd20c86748da
exit code: 0
```

**Output**

```
$ podman-compose version
podman-compose version: 1.0.7
['podman', '--version', '']
using podman version: 4.6.0-rc2
podman-compose version 1.0.7
podman --version
podman version 4.6.0-rc2
exit code: 0
```

**Environment:**
 - OS: CentOS9-Stream
 - podman version: 4.6.0-rc2
 - podman compose version: 0164c1d

**Additional context**

Running `podman run -d --name ftp -p 1082:21 docker.io/delfer/alpine-ftp-server` correctly binds the port.

**Comment by nalderto** [comment]
@Vic-M This is actually a quirk with YAML 1.1.  PyYAML, which podman-compose uses, parses using YAML 1.1.  If you convert `1082:21` from sexagesimal to decimal using a tool like [this](https://planetcalc.com/9214/), you'll see it is 64941, which is the port Podman is forwarding to.  Thus, this is not a bug at all.  This quirk can be avoided by containing ports in quotes, like so 
```
version: "3.8"
services:
  ftp:
    image: "docker.io/delfer/alpine-ftp-server"
    ports:
      - "1082:21"
```

This quirk is actually [documented](https://docs.docker.com/compose/compose-file/05-services/#ports) in the official Docker Compose documentation.  However, since docker-compose has moved to using [Go](https://github.com/docker/compose) and Go's yaml package [claims](https://pkg.go.dev/gopkg.in/yaml.v2#section-readme) to not have this issue, who knows if this still impacts docker-compose.

**Comment by Vic-M** [comment]
It works with the quotes. Thanks!
